Repository hibernate/hibernate-search, pull requests merged in 2020-10, with the labels that each got.

#2385 HSEARCH-4030 Upgrade to Hibernate ORM 5.4.22.Final
  pom.xml
Labels: +1 just push it!

#2392 HSEARCH-4031 Follow-up: Move from Easymock to Mockito
  legacy/integrationtest/jsr352/pom.xml
  legacy/jsr352/core/pom.xml
  legacy/orm/pom.xml
Labels: +1 just push it!

#2395 HSEARCH-4042 Restore the retry() steps in the Jenkinsfile
  Jenkinsfile
  parents/integrationtest/pom.xml
Labels: +1 just push it!

#2397 HSEARCH-2836 Timeouts start when the request is submitted to the client, leading to systematic timeout when client is under heavy load
  integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java
Labels: Ready for review

#2399 HSEARCH-4046 Expose a map of static children by name in the metamodel of object fields
  backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/AbstractElasticsearchIndexSchemaFieldTemplateBuilder.java
  backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/AbstractElasticsearchIndexSchemaObjectNodeBuilder.java
  backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/ElasticsearchIndexSchemaObjectFieldNodeBuilder.java
  backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/ElasticsearchIndexSchemaRootNodeBuilder.java
  backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/dsl/impl/ElasticsearchIndexSchemaValueFieldNodeBuilder.java
  backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexSchemaNodeContributor.java
  backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexSchemaObjectFieldNode.java
  backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexSchemaObjectFieldTemplate.java
  backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexSchemaObjectNode.java
  backend/elasticsearch/src/main/java/org/hibernate/search/backend/elasticsearch/document/model/impl/ElasticsearchIndexSchemaRootNode.java
  backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/AbstractLuceneIndexSchemaFieldTemplateBuilder.java
  backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/AbstractLuceneIndexSchemaObjectNodeBuilder.java
  backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/LuceneIndexSchemaObjectFieldNodeBuilder.java
  backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/LuceneIndexSchemaRootNodeBuilder.java
  backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/dsl/impl/LuceneIndexSchemaValueFieldNodeBuilder.java
  backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaNodeContributor.java
  backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaObjectFieldNode.java
  backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaObjectFieldTemplate.java
  backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaObjectNode.java
  backend/lucene/src/main/java/org/hibernate/search/backend/lucene/document/model/impl/LuceneIndexSchemaRootNode.java
  engine/src/main/java/org/hibernate/search/engine/backend/metamodel/IndexCompositeElementDescriptor.java
  integrationtest/backend/tck/src/main/java/org/hibernate/search/integrationtest/backend/tck/metamodel/IndexFieldDescriptorIT.java
Labels: +1 just push it!

#2404 HSEARCH-4054 Upgrade to JUnit 4.13.1
  pom.xml
Labels: +1 just push it!

#2406 HSEARCH-4024 Upgrade integration tests to the latest version of Spring Boot
  integrationtest/showcase/library/pom.xml
  pom.xml
Labels: Ready for review

#2418 HSEARCH-4021 Avoid to log UNICODE 0xFFFF (and 0xFFFE)
  integrationtest/v5migrationhelper/orm/src/test/java/org/hibernate/search/test/bridge/BridgeTest.java
Labels: +1 just push it!

#2419 HSEARCH-4021 Revert implicit diamond for JDK 8
  integrationtest/mapper/orm/src/test/java/org/hibernate/search/integrationtest/mapper/orm/bootstrap/BootstrapLogsIT.java
Labels: +1 just push it!

#2423 HSEARCH-4021 Flush after a purge in tests to ensure the purge is visible from tests
  integrationtest/showcase/library/src/main/java/org/hibernate/search/integrationtest/showcase/library/repository/indexsearch/IndexSearchDocumentRepositoryImpl.java
Labels: +1 just push it!, Urgent

#2424 HSEARCH-4075 Upgrade to Hibernate Annotations 5.1.1.Final
  pom.xml
Labels: +1 just push it!

#2425 Backport HSEARCH-4075 to branch 5.11 - Upgrade to Hibernate Annotations 5.1.1.Final
  pom.xml
Labels: +1 just push it!
