Repository hibernate/hibernate-search, pull requests merged in 2021-04, with the labels that each got.

#2542 HSEARCH-4196 Upgrade to ORM 5.4.30.Final
  pom.xml
Labels: backport to 5.x

#2541 HSEARCH-4196 Upgrade to ORM 5.4.30.Final
  pom.xml
Labels: backport to 6.0

#2543 HSEARCH-4207 Clarify in README that Hibernate Search is licensed under LGPL v2.1 *or later*
  README.md
Labels: Waiting for CI

#2544 HSEARCH-4211 Use commits instead of rollbacks in the mass indexer
  mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
  mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/HibernateOrmMassIndexingDocumentProducerInterceptor.java
Labels: Urgent, Waiting for CI

#2545 Backport HSEARCH-4211 to branch 6.0 - Use commits instead of rollbacks in the mass indexer
  mapper/orm/src/main/java/org/hibernate/search/mapper/orm/logging/impl/Log.java
  mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/IdentifierConsumerDocumentProducer.java
  mapper/orm/src/main/java/org/hibernate/search/mapper/orm/massindexing/impl/OptionallyWrapInJTATransaction.java
Labels: Urgent, Waiting for CI, backport to 6.0

#2548 Backport HSEARCH-4213 to branch 6.0 - Upgrade to Jackson 2.12.x
  pom.xml
Labels: backport to 6.0

#2558 HSEARCH-4214 follow-up (backport to 6.0): fix tests on Elasticsearch 5.6
  integrationtest/backend/elasticsearch/pom.xml
  integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/bootstrap/ElasticsearchBootstrapIT.java
  integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/testsupport/categories/RequiresSingleModelDialectForMajorVersion.java
Labels: backport to 6.0

#2562 Backport of HSEARCH-4130 Cleanup docker containers
  Jenkinsfile
Labels: backport to 6.0
